# fly.toml app configuration file generated for terminalkiller on 2023-06-01T03:24:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "terminalkiller"
primary_region = "scl"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
